### ISSUE TITLE
missing directory "dh1tw" component in section "How to build" in readme.md

### ISSUE THREAD

**Issue by jmscott** [dh1tw/remoteRotator#15]
In the section "How to build" of readme.md, the directory component appears to be missing
the component "dh1tw".  The line

    cd $GOPATH/src/github.com/remoteRotator

i believe should say

    cd $GOPATH/src/github.com/dh1tw/remoteRotator

i have tested with GOPATH=$HOME/go and no value for GOPATH.  the golang version is go1.13.5 under both mac catalina and high sierra.

**Comment by dh1tw** [comment]
Hi @jmscott,

you are correct! Thanks! I just fixed it and pushed the commit to master. Please let me know if you have experience any further difficulties in the build process (or when using remoteRotator).

**Comment by jmscott** [comment]
no problems.  thanks.
