### ISSUE TITLE
https://github.com/micro/mdns doesn't exist anymore but it is an dep

### ISSUE THREAD

**Issue by failureerror** [dh1tw/remoteRotator#19]
hi, i cant build the rotator:
```
fatal: could not read Username for 'https://github.com': terminal prompts disabled
package github.com/micro/mdns: exit status 128

and the page https://github.com/micro/mdns doesnt exist.
```
thnx

**Comment by dh1tw** [comment]
hey @failureerror,

indeed - this is the same problem as mentioned in https://github.com/dh1tw/remoteAudio/issues/26. The author of the underlying library (go-micro) decided to rename / rebrand / move reorganize the repos during the last weeks. Updating the imports should fix this issue. 
I will try to fix it next weekend.

**Comment by dh1tw** [comment]
I updated the dependencies and bumped to go version to 1.15.
However the error message you mention still remains while downloading the source with 
```go get github.com/dh1tw/remoteRotator```
But that's actually not a problem and you can ignore it.

During the build step (using ```make```), the Github redirect magic does it's trick and `remoteRotator` will just build fine. 

Please let me know if you still encounter problems.

**Comment by dh1tw** [comment]
I finally was able to fix the problem. It was quite a ride upgrading the underlying go-micro framework on which remoteRotator relies for communication. You should now be able to compile remoteRotator without any problems. The CI build process also works for all major platforms. 
Please let me know in case you still encounter any problems!
