### ISSUE TITLE
duplicate attribute in <link> elements

### ISSUE THREAD

**Issue by jmscott** [dh1tw/remoteRotator#5]
a <link> element in the file index.html appears to have duplicate attributes.  see line #9 of https://github.com/dh1tw/remoteRotator/blob/master/html/index.html

**Comment by dh1tw** [comment]
thanks @jmscott, I will fix it in the next release of remoteRotator!

**Comment by dh1tw** [comment]
fixed with feb7f735f1a2dbfffdd6c350b9f2879febee3a61 in the [current development branch "rest"](https://github.com/dh1tw/remoteRotator/tree/rest)
