### ISSUE TITLE
Elevation not supported (K3NG interface)

### ISSUE THREAD

**Issue by MrTom1** [dh1tw/remoteRotator#6]
Hi Tobias,
RemoteRotator is working great using K3NG interface for controlling azimuth, however elevation is not working.
K3NG interface is expecting GS232 command Wxxx yyy (3-digit x:azimuth y:elevation), which seems not to be supported.

Could you please support the "W" command for elevation control? Would be great!

73, Thomas

**Comment by dh1tw** [comment]
Hi Thomas, 

Pablo @ea4tx is preparing a patch for supporting the elevation command. It seems that indeed I forgot to implement it ;-)

It will be fixed in the next release.

**Comment by MrTom1** [comment]
Tobias,
this would be great. When can we expect next release?

**Comment by ea4tx** [comment]
I hope it could be fixed during this week.

73's Pablo EA4TX
[[www.ea4tx.com]](https://ea4tx.com)

**Comment by dh1tw** [comment]
Hey Thomas,
I think we should be able to release version 0.5 within the next two weeks.
Tobias

**Comment by MrTom1** [comment]
Is there also an interest to implement buttons: Park (push), Moon tracking (toggle on/off)?

73, Thomas

**Comment by dh1tw** [comment]
#7

**Comment by dh1tw** [comment]
Hi @MrTom1, 

sorry for the 'slight' delay. I have finally created a new release which you can download on the [releases page](https://github.com/dh1tw/remoteRotator/releases) for your platform of choice.

Feel free to re-open the issue in case something doesn't work as expected.
